#!/usr/bin/env bash

# Generated camel poses are saved as out_##.obj
#build/bin/corrstool Data/face-poses/face-reference.obj Data/head-poses/head-reference.obj Data/out/face_head.cons


# Correspondence phase:
#build/bin/corres_resolve Data/face-poses/face-reference.obj Data/head-poses/head-reference.obj Data/out/face_head.cons [1:10:50]

# horse_ref.obj:     source reference mesh
# camel_ref.obj:     target reference mesh
# horse_camel.cons:  vertex constraints (marker points),
#                      user can specify marker points corrstool.
# [1:10:50] :        closest point iteration procedure:
#                      weight increase from 1 to 50, increment step: 10.


# output files: 
#    out.obj:       deformed source mesh
#    out.tricorrs:  triangle correspondence resolved by corres_resolve


# Deformation transfer phase:
#build/bin/dtrans  Data/face-poses/face-reference.obj Data/head-poses/head-reference.obj Data/face-poses/face-0*.obj



# ...
# There should be 9 output files generated by dtrans, you can inspect'em
# using corrstool, or modelviz.

#build/bin/modelviz Data/out/out_1.obj


#run on face and head

#build/bin/corrstool Data/face-poses/face-reference.obj Data/head-poses/head-reference.obj Data/out/face_head.cons
#build/bin/corres_resolve Data/face-poses/face-reference.obj Data/head-poses/head-reference.obj Data/out/face_head.cons [1:10:200]
#build/bin/dtrans  Data/face-poses/face-reference.obj Data/head-poses/head-reference.obj Data/out/out.tricorrs Data/face-poses/face-*.obj


#build/bin/modelviz Data/face-poses/face-06*.obj
#build/bin/modelviz Data/out/out_7.obj

#run on horse and camel

#build/bin/corrstool Data/face-poses/face-reference.obj Data/head-poses/head-reference.obj Data/obj/horse_camel.cons
#build/bin/corres_resolve  Data/obj/horse_ref.obj Data/obj/camel_ref.obj  Data/obj/horse_camel.cons [1:1:10]
#build/bin/dtrans  Data/obj/horse_ref.obj Data/obj/camel_ref.obj Data/out/out.tricorrs Data/obj/horse-0*.obj
#build/bin/modelviz Data/out/out_2.obj


#run on face and head

# build/bin/corrstool Data/expression66/exp-ref.obj Data/head-poses/head-reference.obj Data/out/face_head.cons
# build/bin/corres_resolve Data/expression66/exp-ref.obj Data/head-poses/head-reference.obj  Data/cons/face_head.cons [1:1:10]
# build/bin/dtrans  Data/expression66/exp-ref.obj Data/head-poses/head-reference.obj Data/out/out.tricorrs Data/expression66/targetB*.obj
#build/bin/ShowSourceOut


#//3dmm
# build/bin/corrstool Data/expression66/exp-ref.obj Data/myface/current_res.obj Data/cons/exp-myface.cons
# build/bin/corres_resolve Data/expression66/exp-ref.obj Data/myface/current_res.obj  Data/cons/exp-myface.cons [1:1:10]
# build/bin/dtrans  Data/expression66/exp-ref.obj Data/head-poses/head-reference.obj Data/out/out.tricorrs Data/expression66/targetB*.obj

#blendshape
# build/bin/corrstool Data/landmarks_3dmesh/exp-ref.obj  Data/blendshape/blendshape.obj Data/cons/landmarks_3dmesh-blendshape.cons
 build/bin/corres_resolve Data/landmarks_3dmesh/exp-ref.obj Data/blendshape/blendshape.obj  Data/cons/landmarks_3dmesh-blendshape.cons [1:1:800]
# build/bin/dtrans  Data/expression66/exp-ref.obj Data/head-poses/head-reference.obj Data/out/out.tricorrs Data/expression66/targetB*.obj